// Generated by CoffeeScript 1.8.0
(function() {
  var buttons, data, handleClick, myListener, panel, popup_selection, selection, tabs;

  buttons = require("sdk/ui/button/action");

  tabs = require("sdk/tabs");

  data = require("sdk/self").data;

  selection = require("sdk/selection");

  panel = require("sdk/panel");

  handleClick = function(state) {
    tabs.open("127.0.0.1:8090");
  };

  myListener = function() {
    console.log("A selection has been made.");
    console.log("title of active tab is " + tabs.activeTab.url);
    if (selection.text) {
      console.log(selection.text);
    }
    popup_selection.port.emit("text-update", {
      text: selection.text,
      url: tabs.activeTab.url
    });
  };

  buttons.ActionButton({
    id: "localhost-link",
    label: "Visit localhost",
    icon: {
      16: "./earth.png",
      32: "./earth.png",
      64: "./earth.png"
    },
    onClick: handleClick
  });

  selection.on("select", myListener);

  popup_selection = panel.Panel({
    width: 600,
    height: 300,
    contentURL: data.url("popup_selection.html"),
    contentScriptFile: [data.url("notice-api.js"), data.url("popup_selection.js")]
  });

  buttons.ActionButton({
    id: "popup_selection",
    label: "Read",
    icon: "./folder.png",
    onClick: function() {
      popup_selection.show();
    }
  });

}).call(this);
